### PR TITLE
update map address

### PR DESCRIPTION
**Pull request by festinalente91**
- There was a error in case there is no address.
- Now if there is not city name, it will show a default city name (for now PINGO).

### CODE REVIEW

**Comment by ochanje210** [comment]
what if response json itself is null or undefined? wouldn't it be throwing error since it is accessing a property of null or undefined?

**Comment by festinalente91** [comment]
@ochanje210 right. updated

**Comment by ochanje210** [comment]
lol good choice. LGTM

**Comment by yuda1124** [comment]
LGTM

**Comment by ochanje210** [comment]
shipit

**Pull request merged**
