### PR TITLE
fixed swiper render not showing problem on iOS

### PR DESCRIPTION
**Pull request by ochanje210**
giving flex on the swiper's wrapper component was the reason.

### CODE REVIEW

**Comment by ovekyc** [comment]
LGTM

**Comment by ovekyc** [comment]
What is Node security?

**Comment by ochanje210** [comment]
It basically checks our app security by inspecting all the modules being used or connected our app. The current vulnerability we are having right now is coming from negotiator in react-native module but, it is not likely a big deal.

**Comment by ochanje210** [comment]
lgtm

**Pull request merged**
